### ISSUE TITLE
Error in passwordInput()

### ISSUE THREAD

**Issue by ginolhac** [daattali/shinyforms#17]
Hi,

I am sorry if I made a stupid mistake, but I cannot reproduce any of the two examples provided in the `README.md`.
The error is

```
Error in passwordInput(ns("adminpw"), NULL, placeholder = "Password") : 
  unused argument (placeholder = "Password")
```

 I tried to split the `ui` and `server` functions into two separate files but I obtained the same error.

Many thanks in advance

```
sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-apple-darwin15.3.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] shinyforms_0.0.0.9000 shiny_0.13.2         
loaded via a namespace (and not attached):
 [1] R6_2.1.2          rsconnect_0.4.2.1 htmltools_0.3.5   tools_3.2.4       Rcpp_0.12.4       digest_0.6.9     
 [7] xtable_1.8-2      httpuv_1.3.3      miniUI_0.1.1      mime_0.4          shinyjs_0.5.2    
```

**Comment by daattali** [comment]
Ah yes, this package is super in development as I said.  `placeholder` was not a valid parameter for `passwordInput()` in shiny, and I added a PR for it

https://github.com/rstudio/shiny/pull/1152

It got incorporated into Shiny today.  If you download the newest shiny version from GitHub, it should work!

But keep in mind this package is still in its very very early stages so it's very likely that whatever you build today with it will not work in a few weeks because I'll probably change how it works

**Comment by ginolhac** [comment]
thanks! it does work using the dev version of `shiny`.
No worries, it can sure be broken, but I find this project really cool and useful. And, you said "don't be shy" so I tried ;)
One thing you could add to the README (on top of using the `shiny` dev version) is to be careful of the folder name for the answers. Because, the `app` is fetching them all even if created by another one.
Thanks again!

**Comment by daattali** [comment]
I just added a dependency on the Github version of shiny, so no need to
include that note in the README. Thank you for bringing that to my
attention though.

Can you explain a bit what you mean by the folder thing? Two different apps
should live in two different folders, so that shouldn't be an issue unless
they're both using an absolute path and it's the same absolute path. Do you
think the form ID should be appended to the folder name?

Please do keep giving useful feedback and your opinions on how this could
be the easiest and simplest user experience. Everything is currently open
to suggestions

**Comment by ginolhac** [comment]
thanks again!
for the folder thing, I meant that if you were trying your two example forms in one Rproj like I did, you end up saving both answers in the same folder `responses`. Then, in the `admin` mode you see all answers.
I tried adding a different question to one form to see how your package deal with unmatched columns:

```
numbers of columns of arguments do not match
```

which is informative to me, even if the error could be improved. But, I like your idea of appending the form ID to the folder name. I don't think having simple folder names _i.e_ `responses`, `answers`, matter, but one want to see only the answers from the right app.

**Comment by daattali** [comment]
If you change the number of questions, it really shouldn't work.  Think about it if you have a database - there is a schema, you define exactly which columns can exist. You can't simply add another question to the form, you'd need to first change the schema of the database.  I haven't mentioned this point in the readme but it is something that I will have to include in the readme/vignette when more work gets done.  There really isn't an ideal solution for this. What if you do change the questions, should we just ignore all the previous answers and only show responses submitted that match the current format of the form?  Not sure what the right behaviour is. The most correct thing would be to tell the user it's completely in their hands - if the questions change, they need to delete or update the previous responses (which isn't ideal, I know)

**Comment by ginolhac** [comment]
I see your point. What about dynamically creating a `md5sum` of the `app.R` and appending this to the folder name? Hence, if the questions changed, they are saved elsewhere.

Another question, in the basic/soccer example, in the `admin` mode I see the answers from the basic form, but not the soccer one. How should it works?
Actually, I see the point of showing the possibilities but from an user point of view, I would prefer the `tabPanel()` to be sections of the same form. Might be not easy to merge them all. Anyway would be nice to avoid lengthy questions in one tab and group them by theme while being part of one form (sections -> pages in google forms).
Sorry I realized we are really off-topic #17

**Comment by daattali** [comment]
That idea does solve the problem. But I'm not sure I like it. I don't like the idea of appending to the folder name because the user explicitly gives a path, and it'd be bad user experience to use a different folder. If he changes the questions 4 times, and he wants to look in the folder of the questions and see the actual files, he would have no idea which folder to look in.  I don't have a good solution yet, but I don't think this is it :)

Yes, the answers from the two forms are in the same folder, that's because I was careless and was just testing and didn't bother using a different folder name. In reality, I shouldn't have both apps using the same folder.

The tabs should not be different sections of the same form. If a form has multiple sections, they should be nagivatable by clicking a "next"/"previous" button, not by seeing all the pages as tabs.  I just put two tabs to show that you can embed a form inside a tab and can have a whole other shiny app outside of it, and to show that you can even embed multiple forms if you need.  

The sections of a form concept is definitely one I thought about a little bit but I don't think I'll add support for it at least until everything else is working. It's a more advanced feature that isn't critical for launch

**Comment by ginolhac** [comment]
yes, I haven't think it through the md5sum. Maybe it could be used only for warning the user. You could register the `md5sum` just like you save the `timestamp`. Then the user could cluster answers according to their form of origin, even if mingle in the same folder.

Ok for the tabPanel thing. This advanced feature is as you said not critical.
I will experience more your package and get back to you with new comments if any. Thanks again for the development!

**Comment by fozy81** [comment]
In my rdatamill package,  I saved the results from a form in long format. So the number of columns didn't change even when new questions added, two key columns 'question' and 'answer' .  This meant different versions of a form could be handled. And the result table remains constant. Saving all results from any number of forms and versions in a single table per app. Happy to share code...etc

**Comment by daattali** [comment]
@fozy81 that works if you don't give the user the ability to choose where the data goes. But it wouldn't work when I want to give the user the freedom to choose where the responses live (ie Google Sheets/Dropbox/SQLite/MySQL/Mongo/local/etc). And allowing the user to choose where the data goes is quite important for me, I don't want to force it to just be local storage

**Comment by fozy81** [comment]
I agree saving data remotely in a database is a key feature (and appreciate your work already on this). May have to forgive my lack of knowledge, but is saving the data in a standard schema advantageous to this? Having a different schema for each form created, means creating a new table  remotely for each form or change in a form. e.g.
standardised form response schema:
Form ID | Question | Answer | Date | Username | Form Version | + (maybe some other session info)

is easier than
Form ID | Date | Favourite Package? | Shoe size | Favourite Colour |Name | Age | Add |... ad infinitum
...
...
Maybe not a problem in noSQL - just place all key pair values in a single column...? And also not a problem if just a single form per shiny app and the form doesn't change/update?

Appreciate you are very busy at the moment. And I have little experience with web-forms. I'm sure there's lots of ways of doing this and you'll pick the one you need.

**Comment by daattali** [comment]
That's a very nosql approach, but I'd prefer to have it more standardized.  Initially I was very set on having it standardized so that it could fit nicely in regular SQL databses, but if it looks like most people don't want that, then maybe your approach would make more sense.  I don't want to pick the one **I need**, I want to do whatever is best for the most users :)  I'm checking out now though, I'll come back to this in a few weeks, thanks for all your input
