### ISSUE TITLE
Would you like to release the updated version of shinyforms?

### ISSUE THREAD

**Issue by lightbrush** [daattali/shinyforms#25]
I find that there are some updated questionnaire types in your demo but cannot be used at the present.

---

In addition to it, the shinyforms is a great work! Thanks~

**Comment by daattali** [comment]
Can you be more specific - what demo do you mean, and what question types do you see there?

**Comment by lightbrush** [comment]
Thanks for you kind reply and really SORRY for my vague description... 

The demo is this [one](http://daattali.com/shiny/mimic-google-form/).

In your demo, I found you showed the **slider** and **select** question type. But they can't be used in your current shinyforms version. 

Last day I tried to update the shinyforms using fozy81's PR, yet the result was not good...  It cannot be run on the shiny 1.0. It seems that with the evolution of shiny, some internal settings of it has changed. Thus it is not compatible with the fozy81's shinyforms patch.

The current version ran well on shiny 1.0. But when I tried to use admin mode, it returns a warning error after I entered password: `names do not match previous names`. There was no data table displayed and if I clicked the download button, nothing could be downloaded.

**Comment by daattali** [comment]
Ah I see. That's not really a demo, that's an app I wrote a long long time before shinyforms. I've had a lot of people ask me how to write apps like that, so I first made a blog post about it, and a long time after that in a hackathon I started shinyforms in an attempt to make it easier to write similar forms.

This package is not ready for use, you can try it if you want but it's not ready and missing a lot of things :) I do want to come back and finish working on it when I can. I'm trying to find funding for it because it'll be quite a bit of work and I don't have much free time. For now you can use it as-is, but I recommend not using it yet :p
